@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

Package "pumlFromJava" {
class Java2Puml
{
}

class PumlClass
{
}

class PumlDiagram
{
}

class PumlDoclet
{
}

class PumlElement
{
}

class PumlEnum
{
}

class PumlInterface
{
}

class PumlPackage
{
}

}

@enduml

