@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

Package "pumlFromJava" {
class Java2Puml
{
+ <<create>> Java2Puml() 
+ {static} main(args : String[]) 
}

class PumlClass
{
- element : TypeElement
- links : ArrayList
- variableList : ArrayList
- methodList : ArrayList
+ <<create>> PumlClass(element : Element) 
+ getName() : String
+ toDCA() : String
+ toDCC() : String
- RetrieveVariables() 
- RetrieveMethods() 
+ getLinks() : ArrayList
}

class PumlDiagram
{
- skinparam : String
- directory : String
- filename : String
- env : DocletEnvironment
+ <<create>> PumlDiagram(env : DocletEnvironment) 
- RetrievePackages() 
+ toDCA() : String
+ toDCC() : String
+ setDirectory(directory : String) 
+ setFilename(filename : String) 
+ getDirectory() : String
+ getFilename() : String
+ getPackageList() : List
}

class PumlDoclet
{
- pumlDiagram : PumlDiagram
- filename : String
- directory : String
- dca : Boolean
+ <<create>> PumlDoclet() 
+ init(locale : Locale, reporter : Reporter) 
+ getName() : String
+ getSupportedOptions() : Set
+ getSupportedSourceVersion() : SourceVersion
+ run(environment : DocletEnvironment)  : Boolean
- InitPumlDiagram(env : DocletEnvironment) 
- WritePuml() 
}

class PumlElement
{
+ <<create>> PumlElement() 
+ {abstract} toDCA() : String
+ {abstract} toDCC() : String
+ {static} GetElementTypeString(element : Element) : String
+ {static} TypeToString(type : TypeMirror) : String
- {static} ExtractTypeString(FullName : String) : String
}

class PumlEnum
{
- element : Element
+ <<create>> PumlEnum(element : Element) 
+ getName() : String
+ toDCA() : String
+ toDCC() : String
+ getEnumElements() : String
}

class PumlInterface
{
- element : Element
- links : ArrayList
- methodList : ArrayList
+ <<create>> PumlInterface(element : Element) 
+ getName() : String
+ toDCA() : String
+ toDCC() : String
+ linksToString() : String
- RetrieveMethods() 
}

class PumlLink
{
- firstElementName : String
- secondElementName : String
- linkType : LinkType
+ <<create>> PumlLink(firstElementName : String, secondElementName : String, linkType : LinkType) 
+ getLinkType() : LinkType
+ getFirstElement() : String
+ getSecondElement() : String
+ {static} RetrieveLinks(element : Element, variableList : ArrayList, methodList : ArrayList) : ArrayList
- {static} getSuperClassLink(element : Element) : PumlLink
- {static} getInterfacesLinks(element : Element) : ArrayList
- {static} getAssociatonsDCA(element : Element, variableList : ArrayList) : ArrayList
- {static} getAssociatonsDCC(element : Element, variableList : ArrayList, methodList : ArrayList) : ArrayList
+ {static} linksToStringDCC(links : ArrayList) : String
+ {static} linksToStringDCA(links : ArrayList) : String
- {static} ExtractContainedTypeString(type : TypeMirror) : String
+ toDCA() : String
+ toDCC() : String
+ equals(obj : Object)  : Boolean
}

class PumlMethod
{
- element : Element
- executableElement : ExecutableElement
- parameters : ArrayList
+ <<create>> PumlMethod(element : Element) 
- RetrieveParameters() 
+ toDCA() : String
+ toDCC() : String
+ getParameters() : ArrayList
+ getElement() : Element
}

class PumlPackage
{
- element : Element
+ <<create>> PumlPackage(element : Element) 
- RetrieveElements() 
+ toDCA() : String
+ toDCC() : String
+ getName() : String
}

class PumlParameter
{
- variableElement : VariableElement
+ <<create>> PumlParameter(variableElement : VariableElement) 
+ toDCA() : String
+ toDCC() : String
+ getVariableElement() : VariableElement
}

class PumlVariable
{
- element : Element
- kind : VariableKind
+ <<create>> PumlVariable(element : Element, kind : VariableKind) 
+ toDCA() : String
+ toDCC() : String
+ getElement() : Element
+ getVariableKind() : VariableKind
+ {static} IsCollection(variable : PumlVariable)  : Boolean
}

class "<<enumeration>>\n LinkType" as LinkType
{
EXTENDS
IMPLEMENTS
DCA_ASSOCIATE
LIST
USE
}

class "<<enumeration>>\n VariableKind" as VariableKind
{
PRIMITIVE
OBJECT
ENUM
}


PumlClass --|> PumlElement

PumlDiagram --|> PumlElement
PumlDiagram " * \n packageList " o--> PumlPackage

PumlDoclet ..|> Doclet


PumlEnum --|> PumlElement

PumlInterface --|> PumlElement

PumlLink --|> PumlElement

PumlMethod --|> PumlElement

PumlPackage --|> PumlElement
PumlPackage " * \n classList " o--> PumlClass
PumlPackage " * \n interfaceList " o--> PumlInterface
PumlPackage " * \n enumList " o--> PumlEnum

PumlParameter --|> PumlElement

PumlVariable --|> PumlElement
PumlVariable ..> PumlVariable : <<use>> 

}

@enduml

