@startuml
'https://plantuml.com/sequence-diagram
skinparam style Strictuml

package javax/lang/model
{
    class AnnotatedConstruct
    {
    getAnnotation(Class<A> annotationType) : <A extends Annotation>
    getAnnotationMirrors() : List<? extends AnnotationMirror> A
    getAnnotationsByType(Class<A> annotationType) : <A extends Annotation> A[]
    }
    enum "<<ENUM>>\nSourceVersion" as SourceVersion
    class UnknownEntityException
}

package javax/lang/model.element
{
}

package javax/lang/model.type
{
}

package javax/lang/model.util
{
}





@enduml